### ISSUE TITLE
Give a decent bio

### ISSUE THREAD

**Issue by TolulopeJoel** [TolulopeJoel/tolulopejoel.github.io#2]
The bio on the homepage currently is a dummy text
- change bio to something decent
- You can be creative with it
- You can make multiple suggestions and just comment them in the code
- You can also decide to volunteer on any of the portfolio projects
This is the recent bio on the homepage of the portfolio:

<img width="1006" alt="Screenshot 2023-10-18 at 8 28 20 PM" src="https://github.com/TolulopeJoel/tolulopejoel.github.io/assets/95661346/e436907b-16b1-4be9-86f6-dbd71668ff24">

**Comment by HamnaJabbar** [comment]
Hi @TolulopeJoel ! could you plz assign this to me?

**Comment by fauxriarty** [comment]
Hey @TolulopeJoel, I'd love to contribute to this

**Comment by ankman007** [comment]
@TolulopeJoel Have made PR for this issue. Please review it.

**Comment by HamnaJabbar** [comment]
Hi @TolulopeJoel ! I have send pr,kindly review.Thankyou

**Comment by fauxriarty** [comment]
Hey @TolulopeJoel! I've created a pr, please check it out and let me know if you have any changes in mind. Thank you!

**Comment by TolulopeJoel** [comment]
> Hey @TolulopeJoel! I've created a pr, please check it out and let me know if you have any changes in mind. Thank you!

Merged
