### ISSUE TITLE
[ENHANCEMENT]: Capitalize the navigation items in the portfolio site. 

### ISSUE THREAD

**Issue by ankman007** [TolulopeJoel/tolulopejoel.github.io#5]
### Issue Description
You will need to capitalize all the navigation items. Also, add hover effects over them. 

### Screenshots
![hvo](https://github.com/TolulopeJoel/tolulopejoel.github.io/assets/108212023/d5d1580b-575b-48ef-8d0e-86fcd31d00e8)
_Screenshot 1_

**Comment by ankman007** [comment]
@TolulopeJoel Working on this issue. Will make PR shortly.

**Comment by TolulopeJoel** [comment]
Hey @ankman007 thanks for your suggestion. You can work on the hovering, but please leave out the capitalisation.
